const test = require('node:test');
const assert = require('node:assert/strict');
const { candidates, localizedData, buildPlan, readInventory, seed, validatePlan, schemaDigest, main } = require('../scripts/seed-projects.cjs');
const projectSchema = require('../src/api/project/content-types/project/schema.json');
function mock() {
 const state = { records: [], technologies: [], failPublish: false, mutations: [] };
 const config = { client: 'postgres', connection: { host: 'test-only', database: 'fixture', schema: 'public' } };
 const documents = uid => uid.includes('technology') ? {
  findMany: async () => structuredClone(state.technologies),
  create: async ({data}) => { const record={...data,documentId:'tech-angular'};state.technologies.push(record);state.mutations.push('technology');return record; },
 } : {
  findMany: async ({filters,locale,status}) => structuredClone(state.records.filter(r=>r.slug===filters.slug&&r.locale===locale&&(!!r.publishedAt)===(status==='published'))),
  findOne: async ({documentId,locale,status}) => structuredClone(state.records.find(r=>r.documentId===documentId&&r.locale===locale&&(!!r.publishedAt)===(status==='published'))),
  create: async ({data,locale}) => { const record={...data,locale,documentId:`doc-${data.slug}`,publishedAt:null,technologies:(data.technologies||[]).map(id=>state.technologies.find(t=>t.documentId===id))};state.records.push(record);state.mutations.push(`create:${locale}`);return structuredClone(record); },
  update: async ({documentId,locale,data}) => { assert.ok(!state.records.some(r=>r.documentId===documentId&&r.locale===locale));for(const field of ['featured','displayOrder','projectType'])assert.equal(data[field],undefined);const shared=state.records.find(r=>r.documentId===documentId);assert.equal(data.slug,shared.slug);const record={...shared,...data,locale,publishedAt:null,technologies:(data.technologies||[]).map(id=>state.technologies.find(t=>t.documentId===id))};state.records.push(record);state.mutations.push(`locale:${locale}`);return structuredClone(record); },
  publish: async ({documentId,locale}) => { if(state.failPublish&&locale==='ar')throw new Error('simulated failure');assert.ok(!state.records.some(r=>r.documentId===documentId&&r.locale===locale&&r.publishedAt));state.records.push({...state.records.find(r=>r.documentId===documentId&&r.locale===locale&&!r.publishedAt),publishedAt:'2026-01-01'});state.mutations.push(`publish:${locale}`);return {}; },
 };
 const app={config:{get:key=>key==='database.connection'?config:'public'},plugin:()=>({service:()=>({find:async()=>[{code:'en'},{code:'ar'}]})}),documents,db:{transaction:async fn=>{const previous=structuredClone(state);try{return await fn({trx:{raw:async()=>{}}});}catch(error){Object.assign(state,previous);throw error;}}}};
 const fetcher=async url=>({ok:true,json:async()=>({data:state.records.filter(r=>r.slug===url.searchParams.get('filters[slug][$eq]')&&r.locale===url.searchParams.get('locale')&&r.publishedAt).map(record=>{const result=structuredClone(record);if(url.searchParams.get('populate')!=='technologies')delete result.technologies;return result;})})});
 return {app,state,fetcher};
}
const options=(plan,fetcher)=>({confirmPlan:plan.digest,publish:true,apiUrl:'https://test.invalid',fetcher});
test('schema and confirmed candidates are preserved; only Angular is assigned',()=>{assert.equal(projectSchema.options.draftAndPublish,true);assert.equal(projectSchema.attributes.slug.pluginOptions.i18n.localized,false);assert.equal(candidates.length,3);assert.equal(candidates.flatMap(c=>c.technologies).join(','),'angular');for(const candidate of candidates)for(const locale of ['en','ar']){assert.equal(localizedData(candidate,locale).description.length,2);assert.equal(localizedData(candidate,locale).myRole,undefined);}});
test('offline dry-run is blocked for production execution and performs no loading',async()=>{const plan=buildPlan({source:'proposal-only',target:null,schema:schemaDigest(),locales:['en','ar'],records:[],technologies:[]});assert.equal(plan.projects.length,3);assert.ok(plan.conflicts.length);assert.throws(()=>validatePlan(plan,plan.digest));await assert.rejects(main(['--dry-run','--apply']));});
test('all six locales are linked, featured, ordered, published and verified; reruns write nothing',async()=>{const {app,state,fetcher}=mock();const plan=buildPlan(await readInventory(app));await seed(app,plan,options(plan,fetcher));assert.equal(state.records.length,12);assert.equal(state.technologies.length,1);for(const [index,candidate]of candidates.entries()){const rows=state.records.filter(r=>r.slug===candidate.slug);assert.equal(new Set(rows.map(r=>r.documentId)).size,1);assert.ok(rows.every(r=>r.featured&&r.displayOrder===index+1));}const count=state.mutations.length;const again=buildPlan(await readInventory(app));await seed(app,again,options(again,fetcher));assert.equal(state.mutations.length,count);});
test('a missing translation is created without overwriting the existing translation',async()=>{const {app,state,fetcher}=mock();const candidate=candidates[1];const existing={...localizedData(candidate,'ar'),title:'Existing editorial title',slug:candidate.slug,locale:'ar',documentId:'existing',featured:true,displayOrder:2,projectType:'Business',technologies:[],publishedAt:null};state.records.push(existing);const before=structuredClone(existing);const plan=buildPlan(await readInventory(app));await seed(app,plan,options(plan,fetcher));assert.deepEqual(state.records.find(r=>r.documentId==='existing'&&r.locale==='ar'&&!r.publishedAt),before);assert.equal(state.records.find(r=>r.slug===candidate.slug&&r.locale==='en').documentId,'existing');});
test('conflicting shared fields, duplicate slugs and stale/tampered plans abort before writes',async()=>{const {app,state,fetcher}=mock();const record={slug:'cyber-imtithal',locale:'en',documentId:'existing',featured:false,displayOrder:0,projectType:'Business'};state.records.push(record);let plan=buildPlan(await readInventory(app));await assert.rejects(seed(app,plan,options(plan,fetcher)));assert.equal(state.mutations.length,0);state.records=[];plan=buildPlan(await readInventory(app));const tampered=structuredClone(plan);tampered.projects[0].featured=false;assert.throws(()=>validatePlan(tampered,plan.digest));state.records.push(record);await assert.rejects(seed(app,plan,options(plan,fetcher)));assert.equal(state.mutations.length,0);state.records.push({...record,documentId:'another'});assert.ok(buildPlan(await readInventory(app)).conflicts.some(c=>c.includes('Multiple documents')));});
test('publication failure rolls back all content; post-commit API failure is reported without duplication',async()=>{const {app,state,fetcher}=mock();let plan=buildPlan(await readInventory(app));state.failPublish=true;await assert.rejects(seed(app,plan,options(plan,fetcher)));assert.equal(state.records.length,0);assert.equal(state.technologies.length,0);state.failPublish=false;plan=buildPlan(await readInventory(app));let apiCalls=0;await assert.rejects(seed(app,plan,options(plan,async()=>({ok:++apiCalls<=2,json:async()=>({data:[]})}))));assert.equal(state.records.length,12);const count=state.mutations.length;plan=buildPlan(await readInventory(app));await seed(app,plan,options(plan,fetcher));assert.equal(state.mutations.length,count);});
test('production calls refuse an unverified backup authorization before any mutations',async()=>{const {app,state,fetcher}=mock();const original=app.config.get;app.config.get=key=>key==='environment'?'production':original(key);const plan=buildPlan(await readInventory(app));await assert.rejects(seed(app,plan,options(plan,fetcher)));assert.equal(state.mutations.length,0);});
test('API permission preflight prevents writes',async()=>{const {app,state}=mock();const plan=buildPlan(await readInventory(app));await assert.rejects(seed(app,plan,options(plan,async()=>({ok:false}))));assert.equal(state.mutations.length,0);});
test('SQL plan is revalidated through SQL and Document Service before writes',async()=>{
 const importer=require('../scripts/seed-projects.cjs');const pg=require('../scripts/postgres-inventory.cjs');const {fixture,database}=require('./postgres-fixture.cjs');
 for(const mode of ['ok','sql-changed','documents-changed']){
  const f=fixture();const {app,state,fetcher}=mock();
  const inventory=await pg.readPostgresInventory(f.query,database,{digest:importer.digest,schemaDigest:importer.schemaDigest,targetFingerprintDatabase:importer.targetFingerprintDatabase});const plan=buildPlan(inventory);
  app.db.transaction=async fn=>fn({trx:{raw:async(sql,values)=>{f.state.isolation='serializable';return f.query(sql,values);}}});
  if(mode==='sql-changed')f.state.links.push({id:1,project_id:99,technology_id:99});
  if(mode==='documents-changed')state.records.push({slug:'grc-platform',locale:'en',documentId:'unexpected',publishedAt:null});
  if(mode==='ok'){await seed(app,plan,options(plan,fetcher));assert.equal(state.records.length,12);}else{await assert.rejects(seed(app,plan,options(plan,fetcher)));assert.equal(state.mutations.length,0);}
 }
});
test('Strapi UID and relations must be supplied when creating a missing localization',async()=>{
 const {app,state,fetcher}=mock();const service=app.documents;app.documents=uid=>{const api=service(uid);if(!uid.includes('project'))return api;const update=api.update;return {...api,update:async params=>{assert.equal(params.data.slug,state.records.find(r=>r.documentId===params.documentId).slug);assert.ok(Array.isArray(params.data.technologies));return update(params);}};};
 const plan=buildPlan(await readInventory(app));await seed(app,plan,options(plan,fetcher));for(const locale of ['en','ar']){const rows=state.records.filter(r=>r.slug==='grc-platform'&&r.locale===locale);assert.equal(rows.length,2);assert.ok(rows.every(r=>r.technologies.length===1&&r.technologies[0].slug==='angular'));}assert.equal(state.records.filter(r=>r.publishedAt).length,6);
});
test('publication failures report their stage and safe validation paths without sensitive details',async()=>{
 const {app,state,fetcher}=mock();const service=app.documents;app.documents=uid=>{const api=service(uid);if(!uid.includes('project'))return api;return {...api,publish:async()=>{const error=new Error('password=DO_NOT_LOG postgres://private/token');error.name='ValidationError';error.details={errors:[{path:['slug'],message:'slug must be defined.',value:'PRIVATE_RECORD'},{path:['PRIVATE_TOKEN'],message:'PRIVATE_MESSAGE',value:'PRIVATE_VALUE'}]};throw error;}};};
 const output=[];const original=console.error;console.error=value=>output.push(value);try{const plan=buildPlan(await readInventory(app));await assert.rejects(seed(app,plan,options(plan,fetcher)));}finally{console.error=original;}
 const event=JSON.parse(output[0]);assert.equal(event.stage,'publication');assert.equal(event.record,'grc-platform/en');assert.equal(event.committed,false);assert.deepEqual(event.diagnostic,{name:'ValidationError',validation:[{path:['slug'],rule:'required'}]});assert.ok(!output.join('').includes('PRIVATE'));assert.ok(!output.join('').includes('DO_NOT_LOG'));assert.equal(state.records.length,0);assert.equal(state.technologies.length,0);
});
test('PostgreSQL diagnostics retain only safe codes and names',()=>{
 const {errorDiagnostic}=require('../scripts/seed-projects.cjs');assert.deepEqual(errorDiagnostic({name:'error',code:'23505',message:'SQL WITH PASSWORD',detail:'PRIVATE',query:'PRIVATE',parameters:['PRIVATE']}),{name:'Error',postgresCode:'23505'});assert.deepEqual(errorDiagnostic({name:'PRIVATE_TOKEN',code:'TOKEN'}),{name:'Error'});
});
